#!/usr/bin/env bash
# script that prints Best School 10 times using a while loop.
# In the 9th iteration print Hi before Best school.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
